# version: '3.8'

# services:
#   backend-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: myapp-backend:latest          # hoặc <dockerhub-username>/myapp-backend:latest
#     container_name: myapp-backend
#     ports:
#       - "3000:3000"                       # host:container
#     environment:
#        - MONGODB_URI=mongodb+srv://minhnhi:12070123a@cluster1.appoae6.mongodb.net/booking-app?retryWrites=true&w=majority&appName=Cluster1
#     restart: always
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
version: '3.8'

services:
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-backend:latest
    container_name: myapp-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://minhnhi:12070123a@cluster1.appoae6.mongodb.net/booking-app?retryWrites=true&w=majority&appName=Cluster1
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
